on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo amazon-linux-extras enable dotnet8
          sudo yum install -y dotnet-sdk-8.0 zip unzip aws-cli

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Publish Project
        run: |
          dotnet publish -c Release -o output

      - name: Package Application
        run: |
          zip -r deploy.zip output/*

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp deploy.zip s3://${{ secrets.S3_BUCKET_NAME }}/deploy.zip

      - name: Deploy with CodeDeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws deploy create-deployment --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
          --deployment-group-name ${{ secrets.DEPLOYMENT_GROUP }} \
          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},key=deploy.zip,bundleType=zip

      - name: Monitor Deployment
        run: |
          DEPLOYMENT_ID=$(aws deploy list-deployments --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} --deployment-group-name ${{ secrets.DEPLOYMENT_GROUP }} --query "deployments[0]" --output text)
          STATUS="InProgress"
          while [ "$STATUS" == "InProgress" ]; do
            sleep 10
            STATUS=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID --query "deploymentInfo.status" --output text)
            echo "Current status: $STATUS"
          done

          if [ "$STATUS" == "Succeeded" ]; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed!"
            exit 1
          fi
